### ISSUE TITLE
tj Decompress Header fails when stitching

### ISSUE THREAD

**Issue by TheSheepMasters** [bp2008/MapStitcher#1]
Hello! I decided to try using this app to create a large map of the United States. I'm able to get the tile downloads just fine, but when attempting to stitch them together, i get this error:

-------------
Exception thrown at 2022-12-18 12:41:19 PM
turbojpegCLI.TJException: tjDecompressHeader3 failed
   at turbojpegCLI.TJDecompressor.setSourceImage(Byte[] jpegImage, Int32 imageSize)
   at MapStitcher.MainForm.<>c__DisplayClass24_0.<btnStitchIntoOne_Click>b__0()
   at MapStitcher.MainForm.BwWorker_DoWork(Object sender, DoWorkEventArgs e)
-------------

I'm not very technically inclined, so I'm not sure what this means, but it appears to be a failure with the use of TurboJpeg within this app. I'd appreciate any help with this!

**Comment by bp2008** [comment]
Hmm.  I doubt there's any more information than that available.  Probably I'll just need to use a different image decoder.  If you paste your exact configuration here, I'll try to replicate and fix the issue.

**Comment by TheSheepMasters** [comment]
Thank you for the quick response! My config is as follows:

<?xml version="1.0"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <BaseURL>https://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png</BaseURL>
  <startLat>49.376963</startLat>
  <startLon>-125.307877</startLon>
  <endLat>22.769160</endLat>
  <endLon>-67.684899</endLon>
  <zoom>5</zoom>
  <downloadThreads>4</downloadThreads>
  <stitchThreads>4</stitchThreads>
</Settings>

I've toyed with the zoom, threads, and exact co-ordinates, to no avail.

**Comment by TheSheepMasters** [comment]
Thank you for the quick response! My configuration is as follows. I've tried modifying the zoom, threads, and exact co-ordinates, with no luck to get it to work.

`<?xml version="1.0"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <BaseURL>https://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png</BaseURL>
  <startLat>49.376963</startLat>
  <startLon>-125.307877</startLon>
  <endLat>22.769160</endLat>
  <endLon>-67.684899</endLon>
  <zoom>5</zoom>
  <downloadThreads>4</downloadThreads>
  <stitchThreads>4</stitchThreads>
</Settings>`

**Comment by bp2008** [comment]
I've just released version 1.1 with some changes that should allow it to work for you.  No idea why it was failing because that configuration worked on my system.

https://github.com/bp2008/MapStitcher/releases

**Comment by TheSheepMasters** [comment]
New version works perfectly, thank you very much! I appreciate you coming back to update a years-old tool for me, especially so quickly!
